spring:
  datasource:
    # 开发环境数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/family_assistant?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

# 开发环境跨域配置
cors:
  config:
    allowed-origins:
      - http://localhost:5173
      - http://127.0.0.1:5173
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    allow-credentials: true

# 开发环境允许更详细的日志
logging:
  level:
    org.springframework.security: debug
    org.springframework.web: debug 